jasypt:
    encryptor:
        password: testing

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/cookncode
    username: postgres
    password: root

endpoints:
  enabled: true
  sensitive: false
