jasypt:
    encryptor:
        password: \${JASYPT_ENCRYPTOR_PASSWORD:}

spring:
  datasource:
    url: ENC(Sfv+Nde172kWkbWPKSO2aCBkGbA+sKL0hO5HjZK0W8hlb/GxFWpyKgiWz4QAHGlIWICrGcO3Baps4TG1zijL7oe+rlAo7wwhyMb2XfgUz3BmaeAhcibKWA==)
    username: ENC(jcgVYsnD068a9uQv65ldiNNJopPAA2Kj)
    password: ENC(a4hBptzxIM+Ye3J4U3ZHUYBb1OCwO8on)
